# Generated by Django 2.0 on 2017-12-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objs', '0005_auto_20170124_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdedication',
            name='commentary',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
